In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/ieee-fraud-detection/sample_submission.csv
/kaggle/input/competitions/ieee-fraud-detection/test_identity.csv
/kaggle/input/competitions/ieee-fraud-detection/train_identity.csv
/kaggle/input/competitions/ieee-fraud-detection/test_transaction.csv
/kaggle/input/competitions/ieee-fraud-detection/train_transaction.csv

In [3]:
PATH = "/kaggle/input/competitions/ieee-fraud-detection"
id= pd.read_csv(PATH+"/train_identity.csv")

In [4]:
id

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144228,3577521,-15.0,145955.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,F3111 Build/33.3.A.1.97
144229,3577526,-5.0,172059.0,NaN,NaN,1.0,-5.0,NaN,NaN,NaN,...,chrome 55.0 for android,32.0,855x480,match_status:2,T,F,T,F,mobile,A574BL Build/NMF26F
144230,3577529,-20.0,632381.0,NaN,NaN,-1.0,-36.0,NaN,NaN,NaN,...,chrome 65.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,Moto E (4) Plus Build/NMA26.42-152
144231,3577531,-5.0,55528.0,0.0,0.0,0.0,-7.0,NaN,NaN,0.0,...,chrome 66.0,24.0,2560x1600,match_status:2,T,F,T,F,desktop,MacOS
144232,3577534,-45.0,339406.0,NaN,NaN,-10.0,-100.0,NaN,NaN,NaN,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,RNE-L03 Build/HUAWEIRNE-L03

In [5]:
tr = pd.read_csv(PATH+"/train_transaction.csv")

In [6]:
tr

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.50,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.00,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.00,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.00,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.00,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590535,3577535,0,15811047,49.00,W,6550,NaN,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590536,3577536,0,15811049,39.50,W,10444,225.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590537,3577537,0,15811079,30.95,W,12037,595.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590538,3577538,0,15811088,117.00,W,7826,481.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590539,3577539,0,15811131,279.95,W,15066,170.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
tr.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
  !pip install mlflow dagshub

Collecting mlflow
  Downloading mlflow-3.11.1-py3-none-any.whl.metadata (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 1.4 MB/s eta 0:00:00
Collecting dagshub
  Downloading dagshub-0.7.0-py3-none-any.whl.metadata (12 kB)
Collecting mlflow-skinny==3.11.1 (from mlflow)
  Downloading mlflow_skinny-3.11.1-py3-none-any.whl.metadata (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.0/50.0 kB 2.1 MB/s eta 0:00:00
Collecting mlflow-tracing==3.11.1 (from mlflow)
  Downloading mlflow_tracing-3.11.1-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.13.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (43.0.3)
Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (7.1.0)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<26 (from mlflow)
  Downloading gunicorn-25.3.0-py3-none-any.whl.metadata (5.5 kB)
Collecting huey<3,>=2.5.4 (from mlflow)
  Downloading huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.3.3)
Requirement already satisfied: pyarrow<24,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (23.0.1)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.47)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (8.3.1)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.11.1->mlflow)
  Downloading databricks_sdk-0.106.0-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.133.0)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (3.1.46)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (26.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (5.29.5)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.2.1)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.41.0)
Collecting appdirs>=1.4.4 (from dagshub)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.12/dist-packages (from dagshub) (13.9.4)
Collecting dacite~=1.6.0 (from dagshub)
  Downloading dacite-1.6.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.12/dist-packages (from dagshub) (9.1.4)
Collecting gql[requests] (from dagshub)
  Downloading gql-4.0.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.12/dist-packages (from dagshub) (0.6.7)
Collecting treelib>=1.6.4 (from dagshub)
  Downloading treelib-1.8.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pathvalidate>=3.0.0 (from dagshub)
  Downloading pathvalidate-3.3.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from dagshub) (2.9.0.post0)
Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (from dagshub) (1.42.70)
Collecting semver (from dagshub)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Collecting dagshub-annotation-converter>=0.2.0 (from dagshub)
  Downloading dagshub_annotation_converter-0.2.0-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.22.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (6.0.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (11.3.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.11.1->mlflow) (4.0.12)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.8-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.23.0->dagshub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->dagshub) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.1.0->dagshub) (2.19.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.3.2)
Requirement already satisfied: botocore<1.43.0,>=1.42.70 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.42.70)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from boto3->dagshub) (0.16.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->dagshub) (0.9.0)
Collecting backoff<3.0,>=1.11.1 (from gql[requests]->dagshub)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (2.47.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.52.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.0.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.11.1->mlflow) (5.0.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.11.1->mlflow) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.11.1->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (2.41.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.4.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.1.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.6.2)
Downloading mlflow-3.11.1-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 71.4 MB/s eta 0:00:00:00:01:01
Downloading mlflow_skinny-3.11.1-py3-none-any.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 74.7 MB/s eta 0:00:00:00:01
Downloading mlflow_tracing-3.11.1-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 47.3 MB/s eta 0:00:00
Downloading dagshub-0.7.0-py3-none-any.whl (273 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.1/273.1 kB 12.5 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading dacite-1.6.0-py3-none-any.whl (12 kB)
Downloading dagshub_annotation_converter-0.2.0-py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 3.3 MB/s eta 0:00:00
Downloading flask_cors-6.0.2-py3-none-any.whl (13 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 5.3 MB/s eta 0:00:00
Downloading gunicorn-25.3.0-py3-none-any.whl (208 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.4/208.4 kB 11.1 MB/s eta 0:00:00
Downloading huey-2.6.0-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.0/77.0 kB 3.5 MB/s eta 0:00:00
Downloading pathvalidate-3.3.1-py3-none-any.whl (24 kB)
Downloading skops-0.14.0-py3-none-any.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 6.3 MB/s eta 0:00:00
Downloading treelib-1.8.0-py3-none-any.whl (30 kB)
Downloading semver-3.0.4-py3-none-any.whl (17 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading databricks_sdk-0.106.0-py3-none-any.whl (879 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 879.5/879.5 kB 31.4 MB/s eta 0:00:00
Downloading graphql_core-3.2.8-py3-none-any.whl (207 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 9.1 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading gql-4.0.0-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 4.0 MB/s eta 0:00:00
Installing collected packages: huey, appdirs, treelib, semver, pathvalidate, gunicorn, graphql-core, dacite, backoff, graphql-relay, gql, skops, graphene, Flask-CORS, databricks-sdk, dagshub-annotation-converter, mlflow-tracing, mlflow-skinny, dagshub, mlflow
  Attempting uninstall: dacite
    Found existing installation: dacite 1.9.2
    Uninstalling dacite-1.9.2:
      Successfully uninstalled dacite-1.9.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.18.1 requires dacite<2,>=1.9, but you have dacite 1.6.0 which is incompatible.
Successfully installed Flask-CORS-6.0.2 appdirs-1.4.4 backoff-2.2.1 dacite-1.6.0 dagshub-0.7.0 dagshub-annotation-converter-0.2.0 databricks-sdk-0.106.0 gql-4.0.0 graphene-3.4.3 graphql-core-3.2.8 graphql-relay-3.2.0 gunicorn-25.3.0 huey-2.6.0 mlflow-3.11.1 mlflow-skinny-3.11.1 mlflow-tracing-3.11.1 pathvalidate-3.3.1 semver-3.0.4 skops-0.14.0 treelib-1.8.0

In [9]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
import mlflow.sklearn

In [10]:
TARGET= "isFraud"
TR_MISS_TH= 0.8
ID_MISS_TH = 0.7
CARDINALITY_TH=6

In [11]:
import mlflow
import dagshub
dagshub.init(repo_owner='lukaLomadze', repo_name='ML_Assignment_2', mlflow=True)
mlflow.set_tracking_uri("https://dagshub.com/lukaLomadze/ML_Assignment_2.mlflow")
mlflow.set_experiment('Decision_Tree')

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=0c7aa58f-1284-4a64-b1fb-52765aff9a04&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=62d47894292e92d02aab248297265af6df6d60e0f0fd7a1822c7c06fc83aec0a

Accessing as lukaLomadze

Initialized MLflow to track repo "lukaLomadze/ML_Assignment_2"

Repository lukaLomadze/ML_Assignment_2 initialized!

2026/05/04 14:08:39 INFO mlflow.tracking.fluent: Experiment with name 'Decision_Tree' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/773ee2cf85374bd4a7fcfc02db6df2fa', creation_time=1777903720003, experiment_id='2', last_update_time=1777903720003, lifecycle_stage='active', name='Decision_Tree', tags={}, trace_location=None, workspace='default'>

# **Cleaning**

In [13]:
from sklearn.base import BaseEstimator, TransformerMixin
class DropHighMissing(BaseEstimator, TransformerMixin):
    def __init__(self, tr_th=TR_MISS_TH, id_th=ID_MISS_TH, identity_cols=None):
        self.tr_th = tr_th
        self.id_th = id_th
        self.identity_cols = identity_cols

    def fit(self, X, y=None):
        id_set = set(self.identity_cols) if self.identity_cols else set()
        keep = []
        for col in X.columns:
            miss_rate = X[col].isnull().mean()
            threshold = self.id_th if col in id_set else self.tr_th
            if miss_rate <= threshold:
                keep.append(col)
        self.cols_ = keep
        return self

    def transform(self, X):
        return X[self.cols_]

In [14]:
tr.shape

(590540, 394)

In [15]:
id.shape

(144233, 41)

In [16]:
train = tr.merge(id, on="TransactionID", how="left")
print(train.head())

   TransactionID  isFraud  TransactionDT  TransactionAmt ProductCD  card1  \
0        2987000        0          86400            68.5         W  13926
1        2987001        0          86401            29.0         W   2755
2        2987002        0          86469            59.0         W   4663
3        2987003        0          86499            50.0         W  18132
4        2987004        0          86506            50.0         H   4497

   card2  card3       card4  card5  ...                id_31  id_32  \
0    NaN  150.0    discover  142.0  ...                  NaN    NaN
1  404.0  150.0  mastercard  102.0  ...                  NaN    NaN
2  490.0  150.0        visa  166.0  ...                  NaN    NaN
3  567.0  150.0  mastercard  117.0  ...                  NaN    NaN
4  514.0  150.0  mastercard  102.0  ...  samsung browser 6.2   32.0

       id_33           id_34  id_35 id_36 id_37  id_38  DeviceType  \
0        NaN             NaN    NaN   NaN   NaN    NaN         NaN
1        NaN             NaN    NaN   NaN   NaN    NaN         NaN
2        NaN             NaN    NaN   NaN   NaN    NaN         NaN
3        NaN             NaN    NaN   NaN   NaN    NaN         NaN
4  2220x1080  match_status:2      T     F     T      T      mobile

                      DeviceInfo
0                            NaN
1                            NaN
2                            NaN
3                            NaN
4  SAMSUNG SM-G892A Build/NRD90M

[5 rows x 434 columns]

In [17]:
y = train[TARGET].copy()

In [18]:
print("train", train.shape)

train (590540, 434)

In [19]:
cat_cols=train.select_dtypes(include='object').columns.tolist()
num_cols= train.select_dtypes(exclude='object').columns.tolist()

In [20]:
with mlflow.start_run(run_name="dt_cleaning"):
    mlflow.log_param("TR_MISS_TH", TR_MISS_TH)
    mlflow.log_param("ID_MISS_TH", ID_MISS_TH)
    mlflow.log_param("Final shape", f"{train.shape[0]} X {train.shape[1]}")
    
    mlflow.log_param("Num cols", len(num_cols))
    mlflow.log_param("Catcols", len(cat_cols))
    mlflow.log_param("Fraud rate", float(y.mean()))

🏃 View run dt_cleaning at: https://dagshub.com/lukaLomadze/ML_Assignment_2.mlflow/#/experiments/2/runs/60106d8de8cd426589d308d2200e86f4
🧪 View experiment at: https://dagshub.com/lukaLomadze/ML_Assignment_2.mlflow/#/experiments/2

# Feature engineering

In [21]:
class FeatureEngineer(BaseEstimator, TransformerMixin):
    def __init__(self, identity_cols=None, identity_ids=None, target=None):
        self.identity_cols = identity_cols
        self.identity_ids  = identity_ids   
        self.target        = target

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()
        if "TransactionDT" in X:
            X["TransactionHour"] = (X["TransactionDT"]// 3600) % 24
            X["TransactionDay"]  = (X["TransactionDT"] //86400) % 7

        if self.identity_ids is not None and "TransactionID" in X.columns:
            X["has_identity"] = X["TransactionID"].isin(self.identity_ids).astype(int)

        drop_cols = []
        if "TransactionID" in X.columns:
            drop_cols.append("TransactionID")
        if self.target and self.target in X.columns:
            drop_cols.append(self.target)
        if drop_cols:
            X = X.drop(columns=drop_cols)

        return X

In [22]:
low_card_cols  = [c for c in cat_cols if train[c].nunique() <= CARDINALITY_TH]
high_card_cols = [c for c in cat_cols if train[c].nunique() >  CARDINALITY_TH]

In [23]:
low_card_cols

['ProductCD',
 'card4',
 'card6',
 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'M9',
 'id_12',
 'id_15',
 'id_16',
 'id_23',
 'id_27',
 'id_28',
 'id_29',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'DeviceType']

In [24]:
high_card_cols

['P_emaildomain', 'R_emaildomain', 'id_30', 'id_31', 'id_33', 'DeviceInfo']

In [25]:
train.shape

(590540, 434)

In [26]:
with mlflow.start_run(run_name="dt_feature_engineering"):
    mlflow.log_param("New features", "TransactionDay, TransactionHour , Has_identity")
    mlflow.log_param("CARDINALITY_TH", CARDINALITY_TH) 
    mlflow.log_param("Low cardinality cols", len(low_card_cols))
    mlflow.log_param("High cardinality cols", len(high_card_cols))

🏃 View run dt_feature_engineering at: https://dagshub.com/lukaLomadze/ML_Assignment_2.mlflow/#/experiments/2/runs/5cf92bd84a9e4a1382b6667019ea7385
🧪 View experiment at: https://dagshub.com/lukaLomadze/ML_Assignment_2.mlflow/#/experiments/2

# Feature selection

# Preprocessor

In [27]:

class Preprocessor(BaseEstimator, TransformerMixin):

    def __init__(self, cardinality_th=10):
        self.cardinality_th = cardinality_th

    def _build(self, X):
        num_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
        cat_cols = X.select_dtypes(include="object").columns.tolist()

        num_pipe = Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
        ])
        
        ord_pipe = Pipeline([
            ("imputer", SimpleImputer(strategy="constant", fill_value="missing")),
            ("encoder", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1))
        ])

        transformers = [("num", num_pipe, num_cols)]
        if cat_cols:
            transformers.append(("ord", ord_pipe, cat_cols))

        return ColumnTransformer(transformers, remainder="drop")

    def fit(self, X, y=None):
        self.ct_ = self._build(X)
        self.ct_.fit(X, y)
        return self

    def transform(self, X):
        return self.ct_.transform(X)

In [28]:
def build_pipeline(max_depth, min_samples_leaf, criterion, class_weight, sampling):

    sampler = SMOTE(random_state=42) if sampling == "smote" else RandomUnderSampler(random_state=42)

    identity_cols = [c for c in id.columns if c != "TransactionID"]
    identity_ids  = set(id["TransactionID"].unique())

    return ImbPipeline([
        ("drop",   DropHighMissing(tr_th=TR_MISS_TH, id_th=ID_MISS_TH, identity_cols=identity_cols)),
        ("feat",   FeatureEngineer(identity_cols=identity_cols, identity_ids=identity_ids, target=TARGET)),
       
        ("prep",   Preprocessor()),
        ("sample", sampler),
        ("model",  DecisionTreeClassifier(
            max_depth=max_depth,
            min_samples_leaf=min_samples_leaf,
            criterion=criterion,
            class_weight=class_weight,
            random_state=42
        ))
    ])

# Training

In [29]:
PARAM_GRID = [
    dict(max_depth=6,  min_samples_leaf=50,  criterion="gini",    class_weight=None,          sampling="smote"),
    dict(max_depth=10, min_samples_leaf=50,  criterion="gini",    class_weight=None,          sampling="smote"),
    dict(max_depth=15, min_samples_leaf=50,  criterion="gini",    class_weight=None,          sampling="smote"),
    dict(max_depth=10, min_samples_leaf=20,  criterion="gini",    class_weight=None,          sampling="smote"),
    dict(max_depth=10, min_samples_leaf=50,  criterion="entropy", class_weight=None,          sampling="smote"),
    dict(max_depth=10, min_samples_leaf=50,  criterion="gini",    class_weight="balanced",    sampling="smote"),
    dict(max_depth=10, min_samples_leaf=50,  criterion="gini",    class_weight=None,          sampling="undersample"),
    dict(max_depth=15, min_samples_leaf=20,  criterion="entropy", class_weight="balanced",    sampling="smote"),
]

CV = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

best_auc = -1
best_params = None
results = []

In [30]:
X=train

In [ ]:
for p in PARAM_GRID:
    with mlflow.start_run(run_name=f"DT_depth={p['max_depth']}, leaf={p['min_samples_leaf']}, crit={p['criterion']}, cw={p['class_weight']}, sampling={p['sampling']}"):

        pipe = build_pipeline(p["max_depth"], p["min_samples_leaf"], p["criterion"], p["class_weight"], p["sampling"])

        scores = cross_val_score(pipe, X, y, cv=CV, scoring="roc_auc", n_jobs=1)
        mean_auc = scores.mean()
        std_auc  = scores.std()

        mlflow.log_params(p)
        mlflow.log_metric("cv_auc_mean", mean_auc)
        mlflow.log_metric("cv_auc_std",  std_auc)

        results.append((p, mean_auc))

        if mean_auc > best_auc:
            best_auc    = mean_auc
            best_params = p

🏃 View run DT_depth=6, leaf=50, crit=gini, cw=None, sampling=smote at: https://dagshub.com/lukaLomadze/ML_Assignment_2.mlflow/#/experiments/2/runs/9493f496ddc34dc39e65e19e9e57e1af
🧪 View experiment at: https://dagshub.com/lukaLomadze/ML_Assignment_2.mlflow/#/experiments/2
🏃 View run DT_depth=10, leaf=50, crit=gini, cw=None, sampling=smote at: https://dagshub.com/lukaLomadze/ML_Assignment_2.mlflow/#/experiments/2/runs/4a7d4406bc9043acb6e1ad78b9322b93
🧪 View experiment at: https://dagshub.com/lukaLomadze/ML_Assignment_2.mlflow/#/experiments/2
🏃 View run DT_depth=15, leaf=50, crit=gini, cw=None, sampling=smote at: https://dagshub.com/lukaLomadze/ML_Assignment_2.mlflow/#/experiments/2/runs/866fc4669ca94fcda56ddb49ad3ae378
🧪 View experiment at: https://dagshub.com/lukaLomadze/ML_Assignment_2.mlflow/#/experiments/2

In [ ]:
print(f"Best params: {best_params}  |  CV AUC: {best_auc}")

best_pipe = build_pipeline(
    max_depth        = best_params["max_depth"],
    min_samples_leaf = best_params["min_samples_leaf"],
    criterion        = best_params["criterion"],
    class_weight     = best_params["class_weight"],
    sampling         = best_params["sampling"],
)

with mlflow.start_run(run_name="DT_best_registered") as run:
    mlflow.log_params(best_params)
    mlflow.log_metric("cv_auc_mean", best_auc)

    best_pipe.fit(X, y)

    model_info = mlflow.sklearn.log_model(
        sk_model        = best_pipe,
        artifact_path   = "model",
        registered_model_name = "DT_Best",
    )

    print(f"Model registered: {model_info.model_uri}")
    print(f"Run ID: {run.info.run_id}")